[variables]
NIXPACKS_PYTHON_VERSION = "3.12"

[phases.build]
cmds = ["pip install -r requirements.txt"]

[phases.start]
cmd = "gunicorn servidor_word_final:app --bind 0.0.0.0:$PORT --timeout 120 --workers 1"
